[package]
name = "seqsieve"
version = "0.1.0"
edition = "2024"

[dependencies]
arrayvec = "0.7"
clap = { version = "4.5", features = ["derive"] }
helicase = { git = "https://github.com/imartayan/helicase.git", branch = "mask" }
indicatif = "0.18"
jwalk = "0.8"
rayon = "1"
